### ISSUE TITLE
About and Contact navigation out of order

### ISSUE THREAD

**Issue by adramalech** [Flink91/ionic2-tabs-and-menu#1]
Hey,

I was going through your awesome template and saw a bug.

In the TabsPage you have 1. home, 2. about, and 3. contact.  However, in the app.components.ts you have 1. home, 2. contact, and 3. about.

So contact and about need to be switched.

I changed the app.components.ts code to this:

  // set our app's pages
  appPages: PageInterface[] = [
    { title: 'Home', component: TabsPage, icon: 'calendar' },
    { title: 'About', component: TabsPage, index: 1, icon: 'information-circle' },
    { title: 'Contact', component: TabsPage, index: 2, icon: 'contacts' }
  ];

**Comment by Flink91** [comment]
Oh yeah good call. Thanks, I changed it!
